### ISSUE TITLE
old json-reference-core in the maven: dl.bintray.com

### ISSUE THREAD

**Issue by anujjainFK** [adjohnson916/jackson-json-reference#22]
currently the version uploaded is 0.1.2, please update the latest one
https://dl.bintray.com/adjohnson916/maven/me/andrz/jackson/jackson-json-reference-core/0.1.2/

**Comment by adjohnson916** [comment]
@anujjainFK Sorry Bintray isn't working right. For now you can get the 0.2.0 JARs here: https://github.com/adjohnson916/jackson-json-reference/releases/tag/jackson-json-reference-0.2.0

**Comment by anujjainFK** [comment]
Thanks, do you want me to update the readMe regarding the same?

**Comment by adjohnson916** [comment]
@anujjainFK Feel free to update the README. Can't promise I'll merge it...

**Comment by adjohnson916** [comment]
@anujjainFK Nevermind, I uploaded 0.2.0 artifacts to Bintray - it should work now. Please let me know if otherwise.

**Comment by adjohnson916** [comment]
@anujjainFK FYI version `0.2.1` is now on Maven Central per https://github.com/adjohnson916/jackson-json-reference/issues/25.

**Comment by AndersDJohnson** [comment]
@anujjainFK Please star to express support, if you still find this useful!
