### ISSUE TITLE
README little mistake

### ISSUE THREAD

**Issue by inad9300** [adjohnson916/jackson-json-reference#24]
In the README file, there is a bizarre line:

`JsonReference processor = new JsonReferenceProcessor();`

Which I believe it should be:

`JsonReferenceProcessor processor = new JsonReferenceProcessor();`

So the type returned by the constructor matches the variable's type.

**Comment by adjohnson916** [comment]
Thanks for catching that typo, @inad9300! Fixed it in master.

**Comment by AndersDJohnson** [comment]
@inad9300 Please star to express support, if you still find this useful!
