### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by tomakehurst** [adjohnson916/jackson-json-reference#25]
Do you have any plans to start publishing this library to Maven Central?

I'm currently working on a Swagger validation library for which it's necessary to be able to resolve JSON refs, so it'd be great to use this library. However, I'm reluctant to ship a lib with dependencies that can't be resolved without adding repositories, as this makes life difficult for folks whose only source of Maven deps is a corporate Nexus/Artifactory installation.

I'm planning to fork this and publish it to a group I'm able to release under for now. Please let me know if this is problematic for you in any way.

Thanks,
Tom

**Comment by adjohnson916** [comment]
@tomakehurst Yes, I do intend to publish this to Maven Central. I was waiting for it to stabilize a bit, but since there hasn't been much activity lately, I might as well push out an initial version. I'll try to find some time to do that before too long.

**Comment by tomakehurst** [comment]
That would be great.

Incidentally I've decided to just shade it into my library's JAR for now rather than publish it. Couldn't face that much Maven wrangling on a Friday!

**Comment by adjohnson916** [comment]
@tomakehurst Now published to Maven Central with version `0.2.1`. Thanks for nudging me to do this!

**Comment by tomakehurst** [comment]
Many thanks!

**Comment by adjohnson916** [comment]
@tomakehurst Is this Swagger validation library of yours open source & available somewhere?

**Comment by tomakehurst** [comment]
Annoyingly I'd almost finished it when the author of this emailed me:https://bitbucket.org/atlassian/swagger-request-validator. So I'm switching my efforts to that now. I might still need to use your lib though as the problem of referenced schemas doesn't look fully solved yet.

**Comment by reactormonk** [comment]
Broke our build because the `0.2.1` published before had a slightly different API. Only noticed after an ivy cache clearing.

**Comment by adjohnson916** [comment]
@reactormonk Looks like you deleted your comment regarding this breaking your build - let me know if there are any relevant details or problems with the 0.2.1 release.

**Comment by reactormonk** [comment]
It was a simple fix. I still had a WTF moment because the build didn't work on a new computer.

**Comment by AndersDJohnson** [comment]
@tomakehurst @reactormonk Please star to express support, if you still find this useful!

**Comment by reactormonk** [comment]
No thanks, I prefer to stay away from Java libraries whenever possible. Scala json libraries (e.g. circe) don't tax my sanity as much.

**Comment by AndersDJohnson** [comment]
@reactormonk If you're relying on this library, more stars would help me remember to support it. But sure.
